name: lib_flutterboost
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_boost:
    git:
      url: 'https://github.com/alibaba/flutter_boost.git'
      ref: '4.0.3'
  get: ^4.6.5
  go_router: ^4.2.8
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  json_annotation: ^4.6.0
  device_info_plus: ^4.0.2
  url_launcher: ^6.1.5
  package_info_plus: ^1.4.3
  oktoast: ^3.2.0
  cached_network_image: ^3.2.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  logging: ^1.0.2 #很久没更新
  rxdart: ^0.27.5
  connectivity_plus: ^2.3.6
  photo_view: ^0.14.0
  flutter_easyrefresh: ^2.2.2
  flutter_swiper: 1.1.6 #很久没更新
  lottie: ^1.4.1
  #dio_flutter_transformer: 3.0.2 #很久没更新，和retrofit、dio冲突
  image_picker: ^0.8.5+3
  multi_image_picker: ^4.8.1 #有替代品
  path_provider: ^2.0.11
  flutter_html: ^3.0.0-alpha.5
  flutter_image_compress: ^1.1.1
  auto_size_text: ^3.0.0
  flutter_markdown: ^0.6.10+3
  expandable: ^5.0.1
  popup_window: ^1.1.2 #很久没更新
  webview_flutter: ^3.0.4
  youtube_player_flutter: ^8.1.0
  visibility_detector: ^0.3.3
  table_calendar: ^3.0.6
  characters: ^1.2.0 #最新版1.2.1，和flutter_test冲突
  launch_review: ^3.0.1
  uuid: ^3.0.6
  protobuf: ^2.1.0
  #calendar: ^0.0.3 不支持flutter2.0
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  floor: ^1.3.0
  emoji_picker_flutter: ^1.3.1
  validators: ^3.0.0
  scroll_to_index: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.2.0
  retrofit_generator: ^4.0.3
  json_serializable: ^6.3.1
  intl_utils: ^2.7.0
  floor_generator: ^1.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.sm.lib_flutterboost
    iosBundleIdentifier: com.sm.libFlutterboost
